---
name: PureEntitiesX
main: revivalpmmp\pureentities\PureEntities
version: 0.7.0
api:
- 3.19.0
load: STARTUP
authors:
- milk0417
- RevivalPMMP
description: Implement all MCPE entities into your worlds
website: https://github.com/RevivalPMMP/PureEntitiesX
permissions:
  pureentities:
    default: op
    description: Allows using all the PureEntities commands
    children:
      pureentities.command: ~
      default: op
      description: Allows using all the PureEntities commands
      children:
        pureentities.command.pesummon:
          default: op
          description: Allows spawning mobs
        pureentities.command.peremove:
          default: op
          description: Allows removal of all non-player entities from loaded chunks
...
